

run:
	mvn compile exec:java -Dexec.mainClass="nia.Main"

run_kasp:
	mvn compile exec:java -Dexec.mainClass="nia.Main" -Dexec.args="/home/igor/1.gcat"

volumes_view:
	mvn compile exec:java -Dexec.mainClass="nia.ui.explorer.volumes.VolumesViewExample"

files_view:
	mvn compile exec:java -Dexec.mainClass="nia.ui.explorer.files.FilesViewExample"